### ISSUE TITLE
Teensy 4.0 Loader DNMS hex-File error line 1

### ISSUE THREAD

**Issue by kokoloresBit** [hbitter/DNMS#11]
Hallo, ich versuche verzweifelt mit dem Teesny Loader 1.52
die verschiedenen Hex-Files DNMS V1.x. x oder Vt.0.4 zu laden.
Der Loader gibt beim Öffnen der Files die Meldung "ihex: parse error line 1" aus.
Was mache ich falsch?
Vielen Dank für die Hilfe im Voraus.
Gruß Thorsten

**Comment by hbitter** [comment]
Hallo Thorsten,
sind die herunter geladenen Files O.K.? Am besten geht das, wenn man das gesamte Repository als Zip herunterlädt.
Schau Dir mit einem Hex-Editor z.B. mal DNMS V1.0.5.ino.hex an, sieht das so aus, wie im angehangenen Bild?
![Bild Hex File DNMS V1 0 5 ino hex](https://user-images.githubusercontent.com/559304/87464870-21fb8a00-c614-11ea-95ab-b3ce3bce0480.jpg)

Wenn nicht, der Tipp das gesamte Repository als Zip File herunterladen.

USB-Verbindung zum Teensy ist O.K.?

Viele Grüße
Helmut

**Comment by hbitter** [comment]
Hallo Thorsten,
noch ein Tipp. Auf der Teensy Loader Seite für Windows von PJRC (https://www.pjrc.com/teensy/loader_win10.html) gibt es ein Blink Beispiel fertig übersetzt als Hex für alle Teensies. Versuch damit mal Deinen Teeny zu flashen. Dann wissen wir, dass die Verbindung zum Teensy O.K. ist und es prinzipiell funktioniert.
Viele Grüße
Helmut

**Comment by kokoloresBit** [comment]
Hallo Helmut,
tatsächlich, das herunterladen als Zip-File ist die Lösung. Ich habe per "Link speichern unter" die hex Files kopiert. Das führt dazu, das der Hex-Datei ein Text hinzugefügt wird: Siehe Auszug..
![Github_DL](https://user-images.githubusercontent.com/59657072/87515270-e4cae280-c67b-11ea-8a83-1f69e3c06a81.jpg)
Nach diesem Text folgt später der Text zur Firmware.
Vielen Dank für die schnelle Hilfe.
Viele Grüße 
Thorsten
