### ISSUE TITLE
Kürzere Messintervalle bzw. echte "Livedaten" möglich?

### ISSUE THREAD

**Issue by gidhap** [hbitter/DNMS#12]
Hallo, 
Erst mal Danke für die tolle Arbeit. Ich hoffe daß sich noch möglichst viele diesem Thema (der community) anschliessen.
Bei mir laufen zwei Lärmsensoren.
Ich möchte neben der Standardauswertung die Messwerte in kürzeren Abständen erfassen um kurze Lärmspitzen zu identifizieren.
Bisher hatte ich mit meinem Sound Meter eine Sekunde bzw. 0.5 Sekunden, leider konnte das keine Langzeitaufzeichnung.
Wie kann ich echte Livedaten des Mikrofons in 0,5 oder 1 sek angezeigt bekommen bzw abgreifen?

**Comment by hbitter** [comment]
Hallo gidhap,

Kurz zur Funktionsweise des DNMS. Es wird intern ca. alle 35ms der aktuelle A-bewertete Schalldruckpegel berechnet aus dem RMS Wert aller digitalisierten Werte dieses Intervalls (44,1 kHz, 16-bit Abtastung). Diese Werte werden weitergerechnet zu dem LAeq Wert bis der Sensor abgefragt wird (z.B. alle 150 Sekunden im Sensor.Community Netz). Alle 35ms wird auch der neue Schalldruckpegel mit dem bisherigen niedrigsten und bisherigen höchsten verglichen und neu abgespeichert, wenn der neue Wert kleiner bzw. größer ist als der bisherige. Diese Werte werden bei Abfrage als LAmin bzw. LAmax ausgegeben d.h. man hat mit LAmax die Spitze in dem abgefragten Intervall. 
Der DNMS ist nicht auf ein Abfrageintervall festgelegt, dies wird vom abfragenden System gesteuert d.h. DNMS kann z.B. im Sekundentakt oder auch jede Stunde abgefragt werden.
Im Sensor.Community Netz ist das Abfrageintervall fest auf 150 Sekunden gesetzt, damit werden die Sensoren "überwacht", ob sie noch aktiv sind und andereseits wird häufigeres senden geblockt, damit es nicht zu überlastungen kommt.
Die Konfiguration der Firmware der NodeMCU erlaubt die freie Wahl des Messintervalls:
![B1](https://user-images.githubusercontent.com/559304/87673694-37d49080-c775-11ea-9b13-9ab2c9f58dc9.jpg)

Allerdings in der Standardversion der Firmware nur bis zu 5 Sekunden herunter. Wenn die Firmware anpasst und selbst übersetzt geht natürlich auch 1 Sekunde. 
Übertragungen ins Sensor.Community Netz sind damit natürlich nicht möglich aber man kann andere Möglichkeiten der Datenspeicherung über dei weiteren APIs benutzen. Ich benutze zu Testzwecken eine Influx Datenbank aud einem lokalen PC. Das kann man direkt in der Firmware einrichten:
![B2](https://user-images.githubusercontent.com/559304/87674347-2b046c80-c776-11ea-89c5-e70b5e60d4b0.jpg)

Anzeige der Werte z.B. mittels Grafana (InfluxDB und Grafana gibt es in kostenlosen Versionen) sieht dann so aus:
![B3](https://user-images.githubusercontent.com/559304/87674676-9a7a5c00-c776-11ea-9009-2d3be9b47215.jpg)

Da Du ja zwei DNMS betreibst, könntest Du die werte von einen ja lokal im Sekundentakt mittels InfluxDB aufzeichnen.

Bei weiteren Fragen kannst Du Dich auch gerne direkt an mich wenden helmut.bitter@t-online.de
Viele Grüße
Helmut

**Comment by gidhap** [comment]
DANKE Helmut, habe Dir noch eine mail geschrieben
