### ISSUE TITLE
Teensy 4.0 und MEMS Alternativen

### ISSUE THREAD

**Issue by domcross** [hbitter/DNMS#2]
Hallo,

Die Firmware für Teensy 4.0 in ja noch in der Entwicklung. Ist schon ein grober Zeithorizont absehbar, wann die Produktionsreife erreicht sein wird?

Das verwendete Mikrofon InvenSense ICS-43434, insbesondere die Variante mit Breakoutboard von Pesky ist in Deutschland schwer zu beschaffen. Gibt es besondere Gründe für genau dieses Modell?
Wie sieht es mit Alternativen aus, z.b. dem Knowles SPH0645 - das gibt es mit Breakoutboard z.B. von Adafruit (Produkt Nr. 3421)? Auf dem Datenblatt sind sich die beiden Mikrofone sehr ähnlich.

Viele Grüße
Dominik

**Comment by Nordrunner01** [comment]
@domcross 

Jupp, sehe ich auch so. Ich schätze zwar die Arbeit von Pesky, aber.......... Allein der Versand. :-/

Ich werde mein Glück mit einem Günstigprodukt vom freundlichen Ali versuchen (so um die 3€ronen, inkl. P&V). Soviel ist da ja nicht drann. Eigentlich ein Breakoutboard.

Gruß

**Comment by glosair** [comment]
I have designed a board to hold a ICS-43434, I2C line driver and the Teensy 4.0 (Same foot print as the Teensy 4.0)

I bought 10 ICS-43434 for just over £20 delivered from Farnell here in the UK.

Tim


![20200226_143710](https://user-images.githubusercontent.com/58359462/75354924-a471f000-58a5-11ea-895f-c57358ec5aeb.jpg)

**Comment by glosair** [comment]
I've also an ESP12F board designed ready to go....    

I'll make the desgignes open source when fully tested.

![IMG_20200322_085543](https://user-images.githubusercontent.com/58359462/77246281-9e113280-6c1d-11ea-8a17-fd17a69a8fe0.jpg)

**Comment by hbitter** [comment]
Firmware for Teensy 4.0 is now available.

**Comment by domcross** [comment]
@hbitter Bitte noch einen Kommentar zu den Alternativen für das MEMS-Mikro ICS-43434, z.B. dem Knowles SPH0645 - das gibt es mit Breakoutboard z.B. von Adafruit (Produkt Nr. 3421)? Auf dem Datenblatt sind sich die beiden Mikrofone sehr ähnlich - könnte man das verwenden?
