### ISSUE TITLE
Lärmmessungen mit Peaks von über 800 dB

### ISSUE THREAD

**Issue by pausenzeichen** [hbitter/DNMS#24]
Hallo,

ich bin kein Experte, eigentlich nur user...habe Feinstaubsensoren und den Lärmsensor von Luftdaten.info mit teensy 4.
Der Sensor ist online, jedoch werden in Abständen immer Peaks dargestellt mit Werten jenseits des physikalisch Möglichen.

Es werden Peaks übermittelt mit Werten > 800 dBA.

Ist da das Mikrofon defekt oder wird falsch ausgelesen? Erfolgt keine Prüfung auf Plausibilität?

Liebe Grüße...ich weiß du hast viel zu tun...deswegen schon einmal dank im Voraus...sensor #49568

**Comment by hbitter** [comment]
Hallo pausenzeichen,
ich habe mir mal die Werte der letzten 5 Tage angesehen (18.09. - 22.09.) (Du kannst die Werte im Archiv von Sensor.community finden https://archive.sensor.community/). Am 18. gab es 2 Ausreißer, am 19. 5, am 20. 2, am 21. 0 und am 22. 5. neben Deiner Beobachtung, dass der Wert dann > 800 dBA ist waren auch einige Einträge mit 0 dabei, was genauso falsch ist.

Ist da das Mikrofon defekt oder wird falsch ausgelesen? 
Das kann ich Dir leider nicht sagen, es kann auch noch etwas ganz anderes sein (z.B. Stromversorgung ...) 

Erfolgt keine Prüfung auf Plausibilität?
Nein, das ist auch gar nicht so einfach. Natürlich ist es einfach eine Abfrage zu machen, ob der Wert z.B. > 120 ist aber was macht man dann? Den Wert einfach wegfallen lassen oder durch den letzten ersetzen. Also kurz gesagt Fehlermangement ist eine komplexe Sache und die ist im Gesamtsystem sicher nicht im gewünschten Maße vorhanden. Das muss dann ja auch durchgängig sein d.h. das man der NodeMCU sagt, es ist ein fehler aufgetreten und auch von da muss es weitergegeben werden. Vor allemn darf eines nicht pasieren, dass man denkt es sei in Ordnung und man bemerkt fehlerhafte Messungen gar nicht. Hier wird wenigstens deutlich, da ist etwas nicht in Ordnung. Frage: Nur was?

So, wie kommen wir weiter?
1. Bitte sende mir die genaue Konfiguration (Mache doch einfach von der lokalen Webseite von den Seiten "Aktuelle Werte", "Gerätestatus" und allen Konfugurationsseiten einen Screenshot)
2. Hardwarekonfiguration - kleine Liste oder Foto
3. Welche Firmware ist auf dem Teensy?
4. Hast Du die Möglichkeit über 1 - 2 Tage an der NodeMCU (oder am Teensy) am USB Port einen PC (Laptop) anzuschließen?
5. Hast Du die Möglichkeit eine eigen InfluxDB einzurichten um die Werte lokal aufzuzeichnen?

Gerne kannst Du mir die Antworten (besonders Screenshots) auch per Mail an helmut.bitter (at) t-online.de zukommen lassen.
Viele Grüße
Helmut
