### ISSUE TITLE
Bestückte Platinen bestellen - CPL File?

### ISSUE THREAD

**Issue by LaPhi** [hbitter/DNMS#27]
Ich würde gerne das AIRROHR V1.4 bestückt bestellen wollen. 
Im Bestellprozess (JLCPCB) kommt die Frage nach einem CPL File (Pick&Place File,Only accept XLS,XLSX,CSV).
Existiert diese Datei in diesem Projekt? Wie könnte ich diese erzeugen?

**Comment by pe0ter** [comment]
https://support.jlcpcb.com/article/84-how-to-generate-the-bom-and-centroid-file-from-kicad

Met vriendelijke groet,
Peter

On 7 Dec 2020, at 09:35, LaPhi <notifications@github.com> wrote:

﻿
Ich würde gerne das AIRROHR V1.4 bestückt bestellen wollen.
Im Bestellprozess (JLCPCB) kommt die Frage nach einem CPL File (Pick&Place File,Only accept XLS,XLSX,CSV).
Existiert diese Datei in diesem Projekt? Wie könnte ich diese erzeugen?

**Comment by hbitter** [comment]
Hallo LaPhi,

nein ein solcher CPL File für die Bestückung existiert bisher nicht. Entweder, wie Peter schon geantwortet hat, selbst erzeugen nach der Anleitung von JLCPCB oder wenn Du ein bestücktes Board kaufen möchtest den Kollegen Franz Hoefle "franz.hoefle (at) buergerforum-gladbeck.de"  fragen, der manchmal Boards vorrätig hat und auch bestückt.
Viele Grüße
Helmut
