### ISSUE TITLE
what happened to type=Laerm

### ISSUE THREAD

**Issue by derkod** [hbitter/DNMS#33]
Dear Helmuth,
Do you maybe understand why the SensorCommunity API to get the DNMS-data is not working for me?
See https://github.com/opendata-stuttgart/meta/issues/158
Thanks!
Derko

**Comment by hbitter** [comment]
Hi Derko,
I don't know anything at the moment about the change that happend. I will ask around what happend and how to solve it. Hopefully I can come back in a short period and give more information.
Regards,
Helmut

**Comment by ricki-z** [comment]
This should work again.
The correct URL for the request would be:
https://data.sensor.community/airrohr/v1/filter/country=NL&type=DNMS%20(Laerm)
The quotation marks were only written to show start and end of the query string.
