### ISSUE TITLE
What do you think of this sensor setup? (Please refer to pictures attached)

### ISSUE THREAD

**Issue by linuxlurak** [hbitter/DNMS#35]
For quite some time I have been working on a compact an easy to assemble design of an environment sensor. It uses an SDS011, BME280 and a DNMS. I'm dreaming of integrating a MultiGeiger (see https://github.com/ecocurious2/MultiGeiger). (Lack of time and know how at the moment to complete this idea...)

Please refer to the following pictures:
Internal arrangement:
![image](https://user-images.githubusercontent.com/3813355/120934654-84afb580-c6ff-11eb-8b81-91577e5fce41.png)
View of BME280
![image](https://user-images.githubusercontent.com/3813355/120934662-88433c80-c6ff-11eb-917e-f3ee38abf7cb.png)
Microphone arm using a goose neck to direct the microphone towards the noise source:
![image](https://user-images.githubusercontent.com/3813355/120934668-8bd6c380-c6ff-11eb-8b74-e41bd2452517.png)
View A of soldered DNMS, here you can see pins soldered in addition to connect SDS011 (V5+GND directly under the ESP32):
![image](https://user-images.githubusercontent.com/3813355/120934866-65655800-c700-11eb-877f-2b55380bfe87.png)
View B of soldered DNMS, here you can see pins soldered in addition to connect SDS011 ((TX/RX oppsite side of DNMS-PCB):
![image](https://user-images.githubusercontent.com/3813355/120934859-59799600-c700-11eb-98a8-ed6b74172d57.png)
Positioning of the sensor (it's about 5-7m away of a street allowed 50km/h):
![image](https://user-images.githubusercontent.com/3813355/120935135-942ffe00-c701-11eb-95e5-2e40fb344452.png)

What do you think of this setup (especially I'm interested in your opinion about the housing, microphone arm, positioning)? Criticism is very welcome!

**Comment by hbitter** [comment]
Hi,

![2021-06-06_23-37](https://user-images.githubusercontent.com/559304/120940956-424aa080-c720-11eb-8ab8-a7152f2918b2.png)

It looks a bit to close to the wall and the ceiling. Would a test be possible: place a second DNMS (or another SPL meter) for a comparision farther away from the wall and the ceiling and compare the measurements over 2 - 3 days. Reflections can easily make a difference of 3 - 5 dB(A) or even more but it has to be measured.
Regards,
Helmut

**Comment by glosair** [comment]
Good Morning Helmut

Looks good

I would question the orientation of the SDS011.
![image](https://user-images.githubusercontent.com/58359462/120973789-48b03b00-c767-11eb-8be2-430b87bb220e.png)

You might want to drill a small drain hole in the back of the enclosure so any condensation will drain out that way instead of into either the BME280 or Mic. 

Regards 

Tim

**Comment by linuxlurak** [comment]
I measured the distances and setup another sensor. Just this moment I had to pack things up for the moment as a heavy storm is coming up. But tomorrow I'll set up everything again. 
![image](https://user-images.githubusercontent.com/3813355/121412226-c2f9de80-c964-11eb-87e6-e9dc721aadee.png)

I measured the last couple of days. I'll post the links soon. Then we can compare the data.

**Comment by linuxlurak** [comment]
The storm passed without hitting us... Weather prognosis was completely off; so sensor is set up again.

Link to Data of Sensor next to the wall (the one 18cm away from the wall and 38cm away from the ceiling with Spaghettiplatten):
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?viewPanel=12&var-node=54519

Link to the other Sensor 80cm away from the wall and the ceiling:
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?orgId=1&viewPanel=12&var-node=54520

I guess my setup is not very scientific... but i try my best.

**Comment by linuxlurak** [comment]
> ![image](https://user-images.githubusercontent.com/58359462/120973789-48b03b00-c767-11eb-8be2-430b87bb220e.png)
@glosair Thanks for this hint! I have to reflect on this fact some more. At the moment I did not think of any moisture accumulating in the case by the SDS011. And I used a small 3D-Printed cover with some small volume to prevent accumulating dust in the housing. 

The BME280 is in the middle mounted on a small round pcb that maches the whole. I think no condensation will drop on the bme280. most likely the condensation will be gathered in the 3d printed cover. Or do you have other experiences? In one of my sensors I mounted a moisture absorber silica gel in a simple casing/holder.

I inted to use the sensors on balconies. Perhaps I should measure the humidity in the housing too to check if there is a problem with condensation.

**Comment by hbitter** [comment]
Hi linuxlurak,

do both DNMS running with the same firmware?

**Comment by linuxlurak** [comment]
Actually I upgraded the firmware on all sensors with V2.0.5. But I did not check after the flashing procedure. Errors by me could be possible. I moved one of the sensor today to its former place and set up another one. Will share the links soon.

Do you have some indication there are two different firmwares used?

**Comment by hbitter** [comment]
No, the question was only to be sure eleminating this point. 
Using firmware 2 will give LAeq values down to 30 dB(A) whereas firmware 1 will go down only up to 36/37 dBA. So you will see the difference only below 40 dB(A).
The differences between the two positions are really big even higher than expected, 1. picture at night at around 2:00:
![Sensor 1-2 nachts](https://user-images.githubusercontent.com/559304/121562809-1aa65180-ca1a-11eb-9f30-c89145948cbe.jpg)
Sensor 2 LAeq comes down to 35/36 dB(A), that is O.K.with firmware 1. So, will be interesting with firmware 2, if it's going down to around 30 dB(A).

2. picture at 14:00 Uhr
![Sensor 1-2 14:00Uhr](https://user-images.githubusercontent.com/559304/121563358-a15b2e80-ca1a-11eb-9e39-50bf14f1e00f.jpg)
Nearly 15 dB(A) difference.

A cross check would be good, position sensor 1 micro close to micro of sensor 2 or the opposite (micro of sensor 2 close to micro of sensor 1)

Regards,
Helmut

**Comment by linuxlurak** [comment]
DNMS next to the wall as before:
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?viewPanel=12&var-node=54519

New measurements with new sensor:
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?orgId=1&viewPanel=12&var-node=63125

I'm setting up a third DNMS to measure attached directly to the mic of the sensor next to the wall. Mmaybe i will only manage this next weekend.

**Comment by linuxlurak** [comment]
An additional note on the installation of the SDS: The manual specifies to protect the SDS011 from light incidence. I have in the picture above in comment https://github.com/hbitter/DNMS/issues/35#issue-912905447 where the sensor is unscrewed, turned the by 90°. Better still is an opaque tube or a hose to take. In any case, the sensor opening must not be aligned against the opening in the housing. The result can be seen here, the impact is dramatic:
![image](https://user-images.githubusercontent.com/3813355/121949579-e81d9100-cd58-11eb-9b93-3b7515a6c3cf.png)

**Comment by linuxlurak** [comment]
Now, during two or three weeks, the following set was measured:
![image](https://user-images.githubusercontent.com/3813355/127292987-562efdae-c794-4f7f-ba17-a5002cd46e04.png)

The result seems to me far from the expected:
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?viewPanel=12&var-node=54519&orgId=1
https://maps.sensor.community/grafana/d/000000004/single-sensor-view-for-map?orgId=1&viewPanel=12&var-node=63125

I'm lost...
