### ISSUE TITLE
Impossible DNMS Values on https://api-rrd.madavi.de/

### ISSUE THREAD

**Issue by terraformer** [hbitter/DNMS#39]
Values on https://api-rrd.madavi.de/grafana/d/BYsfp-xGz/dnms?var-chipID=esp8266-9757414&orgId=1 are way off. On the Sensors Web interface everything looks good:

```
GET r: 200
output debug text to displays...
No newer version available.
.
WiFi connected, IP is: <confidential>
Starting Webserver... <confidential>

ChipId: 9757414

MAC Id: <confidential>
Read DNMS...
Trying DNMS sensor on 0x55ws: debug level ...
R/ DNMS
LAeq: 49.47
LA_MIN: 47.26
LA_MAX: 59.18
----
/R DNMS
## Sending to madavi.de: 
Succeeded - api-rrd.madavi.de
Time for Sending (ms): 241
R/ DNMS
LAeq: 49.14
LA_MIN: 46.96
LA_MAX: 60.33
----
```

Current Firmware: NRZ-2020-134-B3/DE (Apr 8 2021) 
Board: DNMS-T4.0+NodeMCU-V1.5
Teensy4.0 Firmware: DNMS_V2.0.5

Any ideas how to fix this? Sensor seems ok but the values in grafana are impossible and do not match with the sensor log.

**Comment by terraformer** [comment]
seems as if i put this issue on the wrong repo, so i reposted it here: https://github.com/opendata-stuttgart/sensors-software/issues/907 this one here can be closed i suppose.

**Comment by hbitter** [comment]
Hi terraformer,

I was out of town for some days and found your question today. 
I think Pierre-Jean answered your qustion at Sensor.Community GitHub pages.
[Impossible DNMS Values on https://api-rrd.madavi.de/ #907](https://github.com/opendata-stuttgart/sensors-software/issues/907)

Getting some more reports on noise values have  [a look at this page](https://laerm.citysensor.de/l) from Reinhard Fürst (only in German).

Regards,
Helmut
