### ISSUE TITLE
cppcheck warnings

### ISSUE THREAD

**Issue by bertrik** [hbitter/DNMS#40]
cppcheck is a tool to quickly check for obvious errors and weird things in source code.

It found a weird construction in DNMS_V2.0.5.ino:
```
  if (Serial.available()) {
    char c = Serial.read();
    if (c == 'o') c = 'o';
    if (c == 's') c = 's';
  }
```

A statement like "if (c == 'o') c = 'o';" is almost completely useless.
It turns out that variable 'c' is not even used anywhere.

I think this part of the source code can simply be left out.

**Comment by hbitter** [comment]
Hi Bertrik,

you are absolutly right. It' s a leftover from some former test version. 
Thanks for the reminder.

Regards,
Helmut
