### ISSUE TITLE
Building with platformio?

### ISSUE THREAD

**Issue by bertrik** [hbitter/DNMS#41]
Have you considered using the platformio build system?

Platformio allows you to build the firmware from the command line, without using the Arduino IDE.
Specific configurations are set in a configuration file, so you no longer needs build instructions (select option 'X' in the Arduino IDE, etc.). When you require a specific version of a library, you can specify the exact version in the configuration file.
This also makes it possible to build a firmware with a github action, for example you could make it automatically build a "most recent hex" on every commit to the github repository.
With the platformio CLI, toolchains and dependencies are downloaded automatically and cached locally.

I have prepared a version of this project which builds the V2.0.5 firmware with platformio, but I could not test the resulting hex file. If you want, I can send you the hex file and perhaps you can test it.
The platformio change consists basically just of a platformio.ini file.
I had to copy the audio lib locally (but it might be possible to share a single copy with all firmwares).

**Comment by hbitter** [comment]
Hi Bertrik,

I have no plans so far to use platformio - at least not in the near future. 

Next step for DNMS will be hopefully realizing analysis in the frequency-domain by FFT.

Please, send me the hex file nd I will test it. (helmut.bitter (at) t-online.de)

Regards,
Helmut
