### ISSUE TITLE
State of DNMS vs SPS30 problems

### ISSUE THREAD

**Issue by Fux2** [hbitter/DNMS#44]
Hi Helmut,
you are mentioning problems at the readme by the simultaneous usage of DNMS and SPS30 (PM-Sensor).
I have just put this into trial operation by an own made PCB (see attached picturess).
What I see, is that the DNMS shows partly missing values but it seems generally to work --> see also attached screenshot.
Can you already give an update about the missing/wrong value problem?

![jpeg_2021-08-27_17-24-37_1](https://user-images.githubusercontent.com/653791/131151719-e9d7d249-c29f-407f-a7d0-520ac56e8df8.jpeg)
![jpeg_2021-08-27_17-24-37_2](https://user-images.githubusercontent.com/653791/131151729-638d41e0-1f45-4546-b478-504261ddc862.jpeg)
![Bildschirmfoto zu 2021-08-27 17-37-20](https://user-images.githubusercontent.com/653791/131152876-e764dcd7-0a9a-4a91-bd60-af1a25839343.png)

Thanks
Markus

**Comment by hbitter** [comment]
Hi Markus,

I have a version ready that hopefully eleminates the I²C communication problems. I'm at the moment out of town. Next week I will put that version into github.
Regards,
Helmut

**Comment by Fux2** [comment]
Hi Helmut,
thanks for your feedback. I am looking forward in testing the new version.
Regards
Markus

**Comment by Fux2** [comment]
Hallo Helmut,
I am running the v2.1.5 firmware for more than two days now.
Before I ran the v2.0.5 firmware, where I had occasionally wrong values (very big numbers up to a few 100 dB(A)) or missing values.
My first impression after this two days: The big numbers are definitely gone and missing numbers I can't find in InfluxDB at least.
I will ran my test setup further and will report in one week once again.
Best regards
Markus

**Comment by Fux2** [comment]
Hi Helmut,
I am still running the v2.1.5 firmware. Now for more than one week.
It's running rock solid and without any issues.
So everything looks fine!
`Uptime | 8 days, 21 hours, 32 min, 13s -- | --`
`only errors`
`Sensirion SPS30 | 0`
`Number of measurements | 12813

![screenshot](https://user-images.githubusercontent.com/653791/133905519-aed2340e-e4d3-4914-9b5c-407e6da9ac7b.png)
(measurement done inside, pm peak was vacuum cleaner ...)

**Comment by hbitter** [comment]
Hi Markus,
sounds promising - thanks for the tests and your efforts.
Regards,
Helmut
