### ISSUE TITLE
Fragwürdige Messergebnisse bei 200Hz - starke Schwankungen

### ISSUE THREAD

**Issue by imaluschi** [hbitter/DNMS#48]
Andauernd sehr starke Schwankungen der Messergebnisse bei 200Hz. Da die Schwankungen auch bei gehobenen Pegel stattfinden und noch dazu die Schwankungsbreite ansteigt - das kann nicht sein.
Hier die Grafik aus Grafana, Werte werden alle 30 Sekunden zur InfluxDB gesendet. Um 6 Uhr läuten die Kirchenglocken, entsprechend der Pegelanstieg.

![Screenshot_20230211_130957](https://user-images.githubusercontent.com/15073635/218257249-a9c0b7f4-d167-4368-9690-57c95479e7aa.png)

Kommt es hier irgendwo zu einer Signalstörung?

Konfiguration:
Lärmsensor mit Feinstaubsensor SDS011, DHT22 und BME280 (zum Vergleich). Lärmsensor ist etwa 1m von der NodeMCU-Einheit mit verbautem Feinstaubsensor (in Verteilerdose) entfernt, noch dazu "ums Eck".
Firmware Teensy 4.0: DNMS_V4.4.4

![Screenshot_20230211_131146](https://user-images.githubusercontent.com/15073635/218257287-24c7ea4f-b577-4387-9cad-0784e1ec104f.png)

**Comment by imaluschi** [comment]
Ergänzung:
Bei einem zweiten Lärmsensor OHNE Feinstaubsensor und Temperatur-/Feuchtemessung tritt dieses Phänomen nicht auf. Derzeitige Verwendung Indoor. Auch 30 Sekunden Intervall für Übertragung zur InfluxDB.

![Screenshot_20230211_132909](https://user-images.githubusercontent.com/15073635/218258122-dc3f6225-67bf-459d-a011-e5f6cf68a02e.png)
![Screenshot_20230211_133049](https://user-images.githubusercontent.com/15073635/218258124-84a1a931-0003-4feb-ba7f-54de98e84a8f.png)

**Comment by Franz4596** [comment]
Die auf der 200Hz Linie liegenden niedrigen Werte scheinen zusätzliche Messpunkte zu sein ?
Solche "Schwingungen" deuten evtl. auf Aliasingeffekten (Überlagerung) hin.

⁣VG Franz Hoefle

​

**Comment by hbitter** [comment]
Hallo Jürgen

wie Franz schon bemerkt hat, gibt es auf der 200Hz Linie zusätzliche Messpunkte jeweils kurz vor dem richtigen Messpunkt im 30 Sekunden Abstand, wobei die zusätzlichen Messpunkte vom Abstand her zum richtigen Messpunkt schwanken, so wie ich es aus der Grafik sehe:
![Ausschnitt_2023-02-11_15-30](https://user-images.githubusercontent.com/559304/218263983-5982bd74-18d9-47c2-a3b5-32edbf28bbb5.jpg)
d.h. es werden zu dem 30 Sekunden Messintervall noch zusätzliche Werte, die zeitlich asynchron sind, nur für 200Hz dargestellt. Nimmt man nur die 200Hz Werte in des 30 Sekunden Rasters ergibt sich, so wie ich es sehe ein "vernünftiger" Verlauf.
Woher kommen die zusätzlichen Werte?
Ausschließen kann ich nichts auch nicht Beeinflussungen von den anderen Sensoren. Es kann aber auch an der InfluxDB und/oder Grafana liegen. Vorschlag für das weitere Vorgehen:

1. Die weiteren Sensoren an der NodeMCU nacheinander abklemmen. Gehen die Störungen/zusätzlichen Werte dann weg durch das Abklemmen eines Sensors?
2. Grafana Definitionen überprüfen, ist noch ein anderer Messwert definiert, der mit der gleichen Farbe wie der LAeq200z angezeigt wird?
3. InfluxDB: Sind in der Messreihe unter dem gleichen Namen für den LAeq200Hz diese zusätzlichen Messwerte abgelegt?

Viele Grüße
Helmut

**Comment by imaluschi** [comment]
Auweh, peinlich! Habs gefunden. Hab bei den Grafana-Einstellungen bei den 200Hz vergessen den Node anzugeben.
Habe derzeit zwei Sensoren laufen, einen Indoor einen Outdoor, selbes Intervall mit dem zur InfluxDB gesendet wird - die können  natürlich praktisch nie synchron laufen. Durch die fehlende Angabe des Nodes hat Grafana auch die Werte des Indoor-DNMS mit angezeigt, die natürlich niedriger sind als die Outdoor-Werte. Daher die Schwankungen.
Danke für die Hinweise. Darauf, dass Werte zeitlich leicht versetzt waren, bin ich in meiner Hudelei nicht gekommen.

![Screenshot_20230212_091817](https://user-images.githubusercontent.com/15073635/218300606-e4b63fa6-9902-479c-9d44-c2399a05571e.png)
![Screenshot_20230212_092518](https://user-images.githubusercontent.com/15073635/218300607-adca0bcc-a6ee-4245-a77f-e7c0090d21cf.png)

Damit werden nun auch die Werte von gestern (Bild im Ausgangspost) richtig dargestellt.

![Screenshot_20230212_093629](https://user-images.githubusercontent.com/15073635/218301031-acedeea9-1569-46aa-a324-0a710790e1c8.png)

LG Jürgen
