### ISSUE TITLE
Final version IM72D128 pcb's and components?

### ISSUE THREAD

**Issue by pe0ter** [hbitter/DNMS#52]
Good morning Helmut,
Both pcb's regarding IM72D128 are now 7 months in this repository.
I wish to order a bunch of sets with pre-soldered components in China
What are your experiences up-to now? Will there be changes to these pcb's in the near future?
Best regards,
Peter

**Comment by hbitter** [comment]
Hi Peter,

the experiences with IM72D128 are quite good. There will be no changes except, that I will update the files to KiCad Version 7. We just recently did measurements with the first IM72D128 microphones produced by the company Watterott electronic GmbH. I will publish the results here in the repository in a couple of days. The company Watterott electronic GmbH will start with a small batch series. If you are interested, please contact them directly: https://shop.watterott.com/Contact

Regards,
Helmut
