### ISSUE TITLE
WLAN integration not possible

### ISSUE THREAD

**Issue by erduino** [hbitter/DNMS#53]
I can select the WLAN and enter and save the WLAN password, but the NODE MCU does not connect to the selected WLAN. The original WLAN remains. However, the new WLAN SSID is in the input mask.
I'm using a developer board with an ESP07 with an external antenna connection due to range issues.
I use ESPHOME 64bit with Windows 10 and Edge Browser. I've already tried all *.ino.bin versions including the old versions.
Also no API configuration possible like with #50.

**Comment by erduino** [comment]
Hallo Helmut

 

Danke für die schnelle Reaktion.

Interessanterweise werden die Eingabemasken nun mit Edge auf Windows 10 richtig angezeigt. Das einzige was ich gemacht habe ist den PC neu gestartet. Habs dann noch via Windows 7 und Firefox getestet, hier wird im Gegensatz zu Windows 10, das PW airrohrcfg verlangt sonst gehts nicht weiter. Dort stimmen die Maken nun auch wie gewohnt.

 

Trotzdem gelingt es nicht mit dem neuen WLAN zu connecten. Putty bringt nun ff. Meldung:

 


ws: not found ...
ws: not found ...
ws: config page ...
output debug text to displays...
Saving config...
failed to open config file for writing
ws: not found ...
ws: not found ...
ws: not found ...
ws: not found ...
ws: config page ...
begin webserver_config_body_get ...
wifi networks found: 3
ws: wifi ...
ws: not found ...
ws: not found ...
 

nach mehreren Minuten habe ich das WLAN meines PC's (Seymchan) wieder mit dem Internet verbunden. NODEMCU aber immer angestöpselt gelassen.

Nach weiteren mehreren Minuten zeigt Putty plötzlich folgendes:

 

ws: not found ...
ws: not found ...
Connecting to Seymchan
---- Result Webconfig ----
WLANSSID: Seymchan
----
PPD: 0
SDS: 0
PMS: 0
HPM: 0
SPS30: 0
NPM: 0
DHT: 0
DS18B20: 0
HTU21D: 0
BMP: 0
DNMS: 1
DNMS READ SPECTRUM: 0
----
SensorCommunity: 0
Madavi: 0
CSV: 0
----
Autoupdate: 0
 

Das von der NODEMCU aufgespannte Netwerk ist nun nicht mehr sichtbar, er hat eine IP bekommen 

 


Display: 0
LCD 1602: 0
Debug: 3
...SNTP synced: Mon Apr  1 17:59:10 2024

.
WiFi connected, IP is: 192.168.8.104
Starting Webserver... 192.168.8.104

ChipId: 8568660

MAC Id: 84cca882bf54
Read DNMS...
Trying DNMS sensor on 0x55H  ... not found
Check DNMS wiring
Send to :
----
ws: root ...
ws: status ...
ws: root ...
ws: status ...
ws: root ...
ws: config page ...
begin webserver_config_body_get ...
ws: config page ...
output debug text to displays...
Saving config...
failed to open config file for writing
ws: root ...
ws: config page ...
begin webserver_config_body_get ...

 

Immer wenn ich eine Konfig Änderung mache meldet Putty

 

Saving config...
failed to open config file for writing

 

aber die Änderungen wurden übernommen. Hm, alles in allem merkwürdiges Verhalten. 

 

Nun mache ich an der NodeMCU einen Reset

und es beginnt von vorne, er spannt wieder sein WLAN auf und man kann ihn unter 192.168.4.1 erreichen, alle Einstellungen sind wieder weg!?

 


ws: not found ...
ws: config page ...
begin webserver_config_body_get ...
ws: not found ...
ws: config page ...
begin webserver_config_body_get ...
ws: not found ...
ws: not found ...
 

Beste Grüsse

erduino

 

 

Gesendet: Montag, 01. April 2024 um 18:25 Uhr
Von: "Helmut Bitter" ***@***.***>
An: "hbitter/DNMS" ***@***.***>
Cc: "erduino" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [hbitter/DNMS] WLAN integration not possible (Issue #53)


 

Hi erduino,


	can you tray to access the NodeMCU with a diffenrent Web Browser instead of Edge Browser (Mozilla, Chrome, Brave). It is possible that your problem is linked to #50. It may be the case that the WLAN password is not taken over due to incorrect behaviour between the browser and the firmware on the NodeMCU.
	could you run a terminal program on your PC (PuTTY, Cool Term or similar) to get the output of the NodeMCU at startup after input of the new WLAN SSID, password and restart of NodeMCU. That could give information that the NodeMCU tries to connect to the new SSID but with now success, maybe because of not updated password.


Regards,

Helmut

**Comment by hbitter** [comment]
Hallo erduino,

- wieviel Flash Speicher hat das Board, das Du benutzt? Der ESPHome-Flasher zeigt das u.a. an. Wenn das Board nur 1MB hat, funktioniert es nicht mit dem Board. NodeMCU Boards u.a. haben 4MB.
- ein anderes Problem kann noch die Zuordnung der I²C Pins zu den GPIO-Pins sein. Sensor.Community hatte da für SCL GPIO2 und für SDA GPIO0 ursprünglich gewählt. Das führt bei einigen Boards (z.B. Wemos D1 mini) zu Problemen. Deshalb habe ich auf der DNMS Konfigurations Seite die Möglichkeit eingeführt andere GPIOs für die I²C Schnittstelle zu wählen (z.B. SCL = GPIO5 und SDA = GPIO4)

Viele Grüße

Helmut

**Comment by erduino** [comment]
das Board hat leider nur 1 MB Flash Speicher. Das ist mit grosser Wahrscheinlichkeit das Problem.

Schade, das Board mit einem ESP07 Modul und Keramikantenne sowie ext. Antennenanschluss wäre eine gute Alternative zur Verbesserung der Reichweite gewesen (+6dB). 

Bemerkenswert ist aber noch, dass das Board die Integration ins WLAN nach einer gewissen (langen) Zeit dann trotzdem schaft aber eben dann nach einem Stromunterbruch oder Reset die Konfiguration wieder verliert.

 

Aber trotzdem vielen Dank für deine schnelle und hilfreiche Reaktion. Wie immer Super Service.

 

Beste Grüsse

Erwin

 
 

Gesendet: Montag, 01. April 2024 um 23:03 Uhr
Von: "Helmut Bitter" ***@***.***>
An: "hbitter/DNMS" ***@***.***>
Cc: "erduino" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [hbitter/DNMS] WLAN integration not possible (Issue #53)


 

Hallo erduino,


	wieviel Flash Speicher hat das Board, das Du benutzt? Der ESPHome-Flasher zeigt das u.a. an. Wenn das Board nur 1MB hat, funktioniert es nicht mit dem Board. NodeMCU Boards u.a. haben 4MB.
	ein anderes Problem kann noch die Zuordnung der I²C Pins zu den GPIO-Pins sein. Sensor.Community hatte da für SCL GPIO2 und für SDA GPIO0 ursprünglich gewählt. Das führt bei einigen Boards (z.B. Wemos D1 mini) zu Problemen. Deshalb habe ich auf der DNMS Konfigurations Seite die Möglichkeit eingeführt andere GPIOs für die I²C Schnittstelle zu wählen (z.B. SCL = GPIO5 und SDA = GPIO4)


Viele Grüße

Helmut

**Comment by hbitter** [comment]
Hallo Erwin,

eine gute Alternative zum NodeMCU Board ist Wemos D1 mini (pro, lite), da gibt es welche mit Keramikantenne und externem Antennanschluss. Die Boards haben 4MB Flash. Die I²C Schnittstelle muss allerdings auf andere Pins gelegt werden (z.B. SCL = GPIO5/D1 und SDA =GPIO4/D2).

![image](https://github.com/hbitter/DNMS/assets/559304/a0e7d1f0-5e33-49ee-8078-f1301b74604b)

Viele Grüße

Helmut

**Comment by pe0ter** [comment]
There is also a version of the NodeMCU with the ESP-07S chip that contains 4MB of memory.

**Comment by erduino** [comment]
That's right but I didn't find a version with an external antenna, they all only have a PCB antenna

 
 

Gesendet: Dienstag, 02. April 2024 um 09:08 Uhr
Von: "pe0ter" ***@***.***>
An: "hbitter/DNMS" ***@***.***>
Cc: "erduino" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [hbitter/DNMS] WLAN integration not possible (Issue #53)


 

There is also a version of the NodeMCU with the ESP-07S chip that contains 4MB of memory.

**Comment by erduino** [comment]
Hallo Helmut,

 

ja das Board kenne ich und habe es auch für andere Zwecke im Einsatz.

Den Einsatz im DNMS habe ich weniger in Erwägung gezogen wegen der Steckerkompatiblität. Da müsste ich ein Adapterboard machen, deshalb wäre die NodeMCU mit dem ESP07 praktisch gewesen.

Mal schauen, es gibt noch Boards mit ESP32 und externer Antenne. Vielleicht sind die Steckerkompatibel.

 

Schöne Grüsse

Erwin

 

 

 

Gesendet: Dienstag, 02. April 2024 um 08:53 Uhr
Von: "Helmut Bitter" ***@***.***>
An: "hbitter/DNMS" ***@***.***>
Cc: "erduino" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [hbitter/DNMS] WLAN integration not possible (Issue #53)


 

Hallo Erwin,

eine gute Alternative zum NodeMCU Board ist Wemos D1 mini (pro, lite), da gibt es welche mit Keramikantenne und externem Antennanschluss. Die Boards haben 4MB Flash. Die I²C Schnittstelle muss allerdings auf andere Pins gelegt werden (z.B. SCL = GPIO5/D1 und SDA =GPIO4/D2).

image.png (view on web)

Viele Grüße

Helmut

**Comment by hbitter** [comment]
Hallo Erwin,

ich habe versuchsweise mal eine Firmware für ESP8266 mit 1MB Flash erzeugt. Ich habe kein ESP8266 Board mit 1MB und kann das nicht testen. Wenn Du Interesse hast das zu testen, kann ich Dir die Version gerne zusenden. Einfach eine PM an mich (helmut.bitter (at) t-online.de mit deiner Mail Adresse. 

Viele Grüße

Helmut
