### ISSUE TITLE
Would love to give a star

### ISSUE THREAD

**Issue by DefinetlyNotAI** [hbitter/DNMS#55]
But, its perfectly fine now, tell me whenit changes so i may give you a star :)

**Comment by hbitter** [comment]
Hello DefinetlyNotAI,

Why and what should be AI in a noise measurement system?

Best regards,

Helmut

**Comment by DefinetlyNotAI** [comment]
No, u misunderstood me, the number of stars currently is the problem,

Once it changes ill star u :)

**Comment by DefinetlyNotAI** [comment]
U may be the most polite person ever lol
